# Site settings
title: Pintu Bhattacharya Blogs
email: info@pintubhattacharya.com
description: >-
  Write your blog description here. This will appear in your document head meta.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.pintubhattacharya.com"
github_username: pintubhattacharyaa

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed  # This will minify your CSS
  sourcemap: never   # Optional: disable sourcemaps in production

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate  # Add this for pagination

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Pintu Bhattacharya"

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  - README.md
  - LICENSE
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata